# -*- coding: utf-8 -*-
"""fraud-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDNgOp1n-rY_6AaoAVef4P9HdOmh5COF
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

np.random.seed(42)


# STEP 1: Create some simple fake data (like a spreadsheet)


n_normal = 950
n_fraud = 50

# Normal transactions: smaller amounts, "normal" looking pattern
normal_data = {
    "Amount": np.random.normal(50, 20, n_normal),
    "Unusual_Score": np.random.normal(0, 1, n_normal),
    "Class": [0] * n_normal
}

# Fraud transactions: bigger amounts, "weirder" pattern
fraud_data = {
    "Amount": np.random.normal(300, 100, n_fraud),
    "Unusual_Score": np.random.normal(4, 1.5, n_fraud),
    "Class": [1] * n_fraud
}

df = pd.concat([pd.DataFrame(normal_data), pd.DataFrame(fraud_data)], ignore_index=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df["Amount"] = df["Amount"].clip(lower=1)

print("STEP 1: Here is a peek at our data (first 5 rows):")
print(df.head())
print(f"\nTotal transactions: {len(df)}")
print(f"Fraud cases: {df['Class'].sum()}")
print(f"Normal cases: {len(df) - df['Class'].sum()}")


print("\nSTEP 2: Making a chart to LOOK at the data...")

plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x="Amount", y="Unusual_Score", hue="Class", palette=["green", "red"])
plt.title("Transactions: Green = Normal, Red = Fraud")
plt.xlabel("Amount Spent ($)")
plt.ylabel("How Unusual It Looks")
plt.tight_layout()
plt.savefig("chart_1_data_overview.png", dpi=150)

plt.close()

print("Saved: chart_1_data_overview.png")


X = df[["Amount", "Unusual_Score"]]   # the clues (inputs)
y = df["Class"]                        # the answer (fraud or not)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("STEP 3: Split data into {len(X_train)} training rows and {len(X_test)} test rows.")



print("STEP 4: Teaching the computer using Logistic Regression...")

model = LogisticRegression()
model.fit(X_train, y_train)

print("Done! The computer has learned the pattern.")


print("STEP 5: Testing the computer on data it has NEVER seen...")

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print(f"\nAccuracy: {accuracy * 100:.1f}%")
print("(This means the computer correctly guessed Fraud/Normal this % of the time)")


print("\nSTEP 6: Making a chart to show how well it did...")

cm = confusion_matrix(y_test, predictions)

plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Predicted Normal", "Predicted Fraud"],
            yticklabels=["Actual Normal", "Actual Fraud"])
plt.title("How Well Did We Do?")
plt.tight_layout()
plt.savefig("chart_2_results.png", dpi=150)
plt.show()
plt.close()

print("Saved: chart_2_results.png")